/**
 * Terms of Service Screen
 * 
 * Displays the terms of service for the North mobile app.
 * Required for App Store compliance.
 * 
 * Validates: Requirements 20.6
 */

import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';

export default function TermsOfServiceScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
          <Text style={styles.backButtonText}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
      </View>

      <ScrollView style={styles.content} contentContainerStyle={styles.contentContainer}>
        <Text style={styles.lastUpdated}>Last Updated: February 2, 2026</Text>

        <Text style={styles.sectionTitle}>1. Acceptance of Terms</Text>
        <Text style={styles.paragraph}>
          By accessing or using North ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.
        </Text>

        <Text style={styles.sectionTitle}>2. Description of Service</Text>
        <Text style={styles.paragraph}>
          North is a mobile application that provides AI-powered coaching services. The App allows you to:
        </Text>
        <Text style={styles.bulletPoint}>• Create and manage personal context (values, goals, projects, constraints)</Text>
        <Text style={styles.bulletPoint}>• Interact with AI coaches for guidance and decision-making support</Text>
        <Text style={styles.bulletPoint}>• Create custom AI coaches (Pro subscription required)</Text>
        <Text style={styles.bulletPoint}>• Access your coaching conversations across devices</Text>

        <Text style={styles.sectionTitle}>3. User Accounts</Text>
        <Text style={styles.paragraph}>
          To use North, you must:
        </Text>
        <Text style={styles.bulletPoint}>• Be at least 13 years of age</Text>
        <Text style={styles.bulletPoint}>• Provide accurate and complete registration information</Text>
        <Text style={styles.bulletPoint}>• Maintain the security of your account credentials</Text>
        <Text style={styles.bulletPoint}>• Notify us immediately of any unauthorized access</Text>
        <Text style={styles.bulletPoint}>• Be responsible for all activities under your account</Text>

        <Text style={styles.sectionTitle}>4. Subscription Terms</Text>
        <Text style={styles.paragraph}>
          North offers two subscription tiers:
        </Text>
        <Text style={styles.bulletPoint}>• Free Tier: Limited to 3 context items, access to default coaches</Text>
        <Text style={styles.bulletPoint}>• Pro Tier: Unlimited context items, custom coach creation</Text>
        
        <Text style={styles.paragraph}>
          Pro Subscription Details:
        </Text>
        <Text style={styles.bulletPoint}>• Monthly: $9.99/month, auto-renewing</Text>
        <Text style={styles.bulletPoint}>• Annual: $79.99/year, auto-renewing</Text>
        <Text style={styles.bulletPoint}>• Payment charged to your Google Play or Apple App Store account</Text>
        <Text style={styles.bulletPoint}>• Auto-renewal can be disabled in account settings</Text>
        <Text style={styles.bulletPoint}>• Cancellation takes effect at the end of the current billing period</Text>
        <Text style={styles.bulletPoint}>• No refunds for partial periods</Text>

        <Text style={styles.sectionTitle}>5. Acceptable Use</Text>
        <Text style={styles.paragraph}>
          You agree NOT to:
        </Text>
        <Text style={styles.bulletPoint}>• Use the App for any illegal purpose</Text>
        <Text style={styles.bulletPoint}>• Attempt to gain unauthorized access to our systems</Text>
        <Text style={styles.bulletPoint}>• Reverse engineer or decompile the App</Text>
        <Text style={styles.bulletPoint}>• Share your account with others</Text>
        <Text style={styles.bulletPoint}>• Use the App to harass, abuse, or harm others</Text>
        <Text style={styles.bulletPoint}>• Submit malicious code or viruses</Text>
        <Text style={styles.bulletPoint}>• Scrape or extract data from the App</Text>

        <Text style={styles.sectionTitle}>6. AI-Generated Content</Text>
        <Text style={styles.paragraph}>
          Important disclaimers about AI coaching:
        </Text>
        <Text style={styles.bulletPoint}>• AI responses are generated by machine learning models and may contain errors</Text>
        <Text style={styles.bulletPoint}>• North is not a substitute for professional advice (medical, legal, financial, etc.)</Text>
        <Text style={styles.bulletPoint}>• You are responsible for evaluating and acting on AI suggestions</Text>
        <Text style={styles.bulletPoint}>• We do not guarantee the accuracy or completeness of AI responses</Text>
        <Text style={styles.bulletPoint}>• AI coaches should not be used for emergency situations</Text>

        <Text style={styles.sectionTitle}>7. Intellectual Property</Text>
        <Text style={styles.paragraph}>
          Ownership:
        </Text>
        <Text style={styles.bulletPoint}>• You retain ownership of your user content (context, messages, custom coaches)</Text>
        <Text style={styles.bulletPoint}>• We retain ownership of the App, default coaches, and all related IP</Text>
        <Text style={styles.bulletPoint}>• You grant us a license to use your content to provide the service</Text>
        <Text style={styles.bulletPoint}>• We may use anonymized data for analytics and improvements</Text>

        <Text style={styles.sectionTitle}>8. Data and Privacy</Text>
        <Text style={styles.paragraph}>
          Your privacy is important to us. Please review our Privacy Policy for details on how we collect, use, and protect your data. By using North, you consent to our data practices as described in the Privacy Policy.
        </Text>

        <Text style={styles.sectionTitle}>9. Termination</Text>
        <Text style={styles.paragraph}>
          We may suspend or terminate your account if:
        </Text>
        <Text style={styles.bulletPoint}>• You violate these Terms</Text>
        <Text style={styles.bulletPoint}>• You engage in fraudulent activity</Text>
        <Text style={styles.bulletPoint}>• Required by law</Text>
        <Text style={styles.bulletPoint}>• We discontinue the service</Text>
        
        <Text style={styles.paragraph}>
          You may delete your account at any time from Settings. Upon termination, your data will be deleted as described in our Privacy Policy.
        </Text>

        <Text style={styles.sectionTitle}>10. Disclaimers</Text>
        <Text style={styles.paragraph}>
          THE APP IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        </Text>
        <Text style={styles.paragraph}>
          We do not guarantee:
        </Text>
        <Text style={styles.bulletPoint}>• Uninterrupted or error-free service</Text>
        <Text style={styles.bulletPoint}>• Accuracy of AI responses</Text>
        <Text style={styles.bulletPoint}>• Specific results from using the App</Text>

        <Text style={styles.sectionTitle}>11. Limitation of Liability</Text>
        <Text style={styles.paragraph}>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE APP.
        </Text>
        <Text style={styles.paragraph}>
          Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.
        </Text>

        <Text style={styles.sectionTitle}>12. Changes to Terms</Text>
        <Text style={styles.paragraph}>
          We may modify these Terms at any time. We will notify you of material changes via email or in-app notification. Continued use of the App after changes constitutes acceptance of the new Terms.
        </Text>

        <Text style={styles.sectionTitle}>13. Governing Law</Text>
        <Text style={styles.paragraph}>
          These Terms are governed by the laws of [Your Jurisdiction]. Any disputes shall be resolved in the courts of [Your Jurisdiction].
        </Text>

        <Text style={styles.sectionTitle}>14. Contact Information</Text>
        <Text style={styles.paragraph}>
          For questions about these Terms, contact us at:
        </Text>
        <Text style={styles.bulletPoint}>• Email: support@northapp.com</Text>
        <Text style={styles.bulletPoint}>• In-app: Settings → Support</Text>

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            By using North, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E4E4E7',
  },
  backButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center' as const,
  },
  backButtonText: {
    fontSize: 16,
    color: '#3B82F6',
    fontWeight: '500',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#09090B',
    flex: 1,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 24,
    paddingBottom: 48,
  },
  lastUpdated: {
    fontSize: 14,
    color: '#71717A',
    marginBottom: 24,
    fontStyle: 'italic',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#09090B',
    marginTop: 24,
    marginBottom: 12,
  },
  paragraph: {
    fontSize: 16,
    color: '#3F3F46',
    lineHeight: 24,
    marginBottom: 12,
  },
  bulletPoint: {
    fontSize: 16,
    color: '#3F3F46',
    lineHeight: 24,
    marginBottom: 8,
    paddingLeft: 8,
  },
  footer: {
    marginTop: 32,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: '#E4E4E7',
  },
  footerText: {
    fontSize: 14,
    color: '#71717A',
    textAlign: 'center',
    fontStyle: 'italic',
  },
});
