[project]
id = "6f8dc722-17cf-4189-9e28-36add81db450"
service = "2c555a37-5e4c-4a8d-b8e8-eae8734d90fb"

[build]
builder = "NIXPACKS"
buildCommand = "python -m ensurepip --upgrade && python -m pip install --upgrade pip && python -m pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
